sudo: required
services:
  - docker

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    test -e Gemfile || cat <<EOF > Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

env:
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=ceph-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=ceph-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=control-cluster
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=control-cluster
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=control-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=control-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=gpfs-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=gpfs-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=hp3par-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=hp3par-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=lefthand-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=lefthand-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=solidfire-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=solidfire-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=storwize-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=storwize-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=volume-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=volume-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=vsp-single
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=vsp-single
    - PLATFORM=trevorj/salty-whales:trusty OS_VERSION=mitaka SUITE=volume-single-barbican
    - PLATFORM=trevorj/salty-whales:xenial OS_VERSION=ocata SUITE=volume-single-barbican

before_script:
  - set -o pipefail
  - make test | tail

script:
  - test ! -e .kitchen.yml || bundle exec kitchen converge ${SUITE} || true
  - test ! -e .kitchen.yml || bundle exec kitchen verify ${SUITE} -t tests/integration

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6123573504759330786b
    on_success: change  # options: [always|never|change] default: always
    on_failure: never  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
    on_cancel: never    # options: [always|never|change] default: always
    on_error: never    # options: [always|never|change] default: always
  email: false
